name: Deploy ReadTheDocs

on:
  push:
    branches: [main, develop]
    paths:
      - 'docs/**'
      - '.readthedocs.yaml'
      - 'package_maximizer/**'
      - 'README.md'
  workflow_dispatch:

permissions: {}

jobs:
  trigger-rtd:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RTD Build
        uses: readthedocs/actions@v2
        with:
          account: dominicusin
          project: package-maximizer
          token: ${{ secrets.RTD_TOKEN }}
        continue-on-error: true